create table Band (id int8 not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Band (id  bigserial not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Band (id  bigserial not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Band (id  bigserial not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Location (id  bigserial not null, address varchar(255) not null, capacity int4 not null, name varchar(255) not null, primary key (id))
create table Band (id  bigserial not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Location (id  bigserial not null, address varchar(255) not null, capacity int4 not null, name varchar(255) not null, primary key (id))
create table Band (id  bigserial not null, musicStyle varchar(255), name varchar(255), primary key (id))
create table Location (id  bigserial not null, address varchar(255) not null, capacity int4 not null, name varchar(255) not null, primary key (id))
