drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Location cascade
drop table if exists Band cascade
drop table if exists Location cascade
drop table if exists Band cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
