drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Band cascade
drop table if exists Location cascade
drop table if exists Band cascade
drop table if exists Location cascade
drop table if exists Band cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table Location drop constraint FKjec1acht3i3bko7702cajctl0
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
drop table if exists Band cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists Location cascade
alter table Cart drop constraint FK7toxf0y2a3mewe83du44h29fi
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table LineItem drop constraint FK99hs9f960ak8l7g15xfntdv2y
alter table LineItem drop constraint FK5dyn1ap0vyk1fdmtqmrtwsa55
alter table Ticket drop constraint FKsotv3qctce5ggaewd002dd71s
alter table users drop constraint FKri6ogcunypjm24gonwvo6lbfs
drop table if exists Band cascade
drop table if exists Cart cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists LineItem cascade
drop table if exists Location cascade
drop table if exists Ticket cascade
drop table if exists users cascade
alter table Cart drop constraint FK7toxf0y2a3mewe83du44h29fi
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table LineItem drop constraint FK99hs9f960ak8l7g15xfntdv2y
alter table LineItem drop constraint FK5dyn1ap0vyk1fdmtqmrtwsa55
alter table Ticket drop constraint FKsotv3qctce5ggaewd002dd71s
alter table users drop constraint FKri6ogcunypjm24gonwvo6lbfs
drop table if exists Band cascade
drop table if exists Cart cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists LineItem cascade
drop table if exists Location cascade
drop table if exists Ticket cascade
drop table if exists users cascade
alter table Cart drop constraint FK7toxf0y2a3mewe83du44h29fi
alter table Event drop constraint FKgdruo5qb3kca4ohxo14cedene
alter table event_bands drop constraint FK2f226i26lxgmrpvkhoj4j8enm
alter table event_bands drop constraint FKrm32iw4wcb3itygg4tf72f7je
alter table LineItem drop constraint FK99hs9f960ak8l7g15xfntdv2y
alter table LineItem drop constraint FK5dyn1ap0vyk1fdmtqmrtwsa55
alter table Ticket drop constraint FKsotv3qctce5ggaewd002dd71s
alter table users drop constraint FKri6ogcunypjm24gonwvo6lbfs
drop table if exists Band cascade
drop table if exists Cart cascade
drop table if exists Event cascade
drop table if exists event_bands cascade
drop table if exists LineItem cascade
drop table if exists Location cascade
drop table if exists Ticket cascade
drop table if exists users cascade
